### PR TITLE
new options and preset update

### PR DESCRIPTION
**Pull request by crimsonvspurple**

### CODE REVIEW

**Comment by FlorianWendelborn** [comment]
While it's appreciated that you try to fix the `CRLF`-issue, I won't merge until you revert that change and fix the formatting issues. The thing is, that I want the `CRLF` to only exist, when you are on a Windows machine, since `\n` is the right choice on Mac & Linux and I don't want to break them instead.

Other than that thanks for your work, judging from the code this should work fine. :neckbeard:

**Comment by FlorianWendelborn** [comment]
dodekeract/manta-config-engine-app#57

**Comment by crimsonvspurple** [comment]
I believe CRLF works fine on Mac/Linux, does it not?

~99% dota players use windows and default editor in that is notepad. So it makes sense to make CRLF default unless anything breaks on Mac/Linux because of CRLF.

**Comment by FlorianWendelborn** [comment]
I'm quite sure there will be some things that break on these systems. And I'm one of the 1% of Linux Dota Players, so I don't want to risk it. I'll see if I can find a better solution later.

I may make it an engine setting or auto-detect the OS if possible.

**Comment by FlorianWendelborn** [comment]
Looks good, what about calling it `smartMultiUnitCast` instead of `smartMultiunitCast`? IMHO that's the better capitalization.

**Comment by FlorianWendelborn** [comment]
Your config seems to still use the old format, also since you will need another commit anyway, you should maybe change the setting description to include `Multi-Unit` instead of `Multiunit`.

**Comment by FlorianWendelborn** [comment]
Thanks, merged.

**Pull request merged**
